SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `historik` (
  `username` varchar(30) NOT NULL,
  `programName` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `historik` (`username`, `programName`) VALUES
('Oliwer', 'Strength'),
('Tilda', 'Powerlifting'),
('Oliwer', 'Strength'),
('Oliwer', 'Endurance'),
('Tilda', 'Strength'),
('Tilda', 'Strength'),
('Tilda', 'Strength'),
('Tilda', 'Strength'),
('Tilda', 'Endurance'),
('Oliwer', 'Endurance'),
('Oliwer', 'Powerlifting'),
('Oliwer', 'Strength'),
('Oliwer', 'Strength'),
('Oliwer', 'Powerlifting'),
('Oliwer', 'Strength'),
('Oliwer', 'Powerlifting'),
('Oliwer', 'Endurance'),
('Oliwer', 'Powerlifting'),
('Oliwer', 'Endurance'),
('Oliwer', 'Strength'),
('Oliwer', 'Strength'),
('Angelina', 'Powerlifting'),
('Tilda', 'Strength'),
('Tilda', 'Endurance'),
('Tilda', 'Strength'),
('Tilda', 'Powerlifting'),
('Tilda', 'Strength'),
('Oliwer', 'Strength'),
('Elsa', 'Strength'),
('Elsa', 'Powerlifting'),
('Greger', 'Strength'),
('Greger', 'Endurance'),
('Greger', 'Strength');


CREATE TABLE `login` (
  `username` varchar(30) NOT NULL,
  `password` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `login` (`username`, `password`) VALUES
('Angelina', 'Blomma123'),
('Elsa', 'Elsa'),
('Greger', 'Greger'),
('Luke', 'Luke'),
('Oliwer', 'Oliwer'),
('tilda', 'admin');

CREATE TABLE `träningskategori` (
  `KategoriNamn` varchar(30) NOT NULL,
  `minRep` int(11) NOT NULL,
  `maxRep` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `träningsprogram` (
  `Program-ID` int(11) NOT NULL,
  `username` varchar(30) NOT NULL,
  `KategoriNamn` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `träningsövning` (
  `ÖvningsNamn` varchar(30) NOT NULL,
  `Typ` varchar(30) NOT NULL,
  `Muskelgrupp` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `träningsövning` (`ÖvningsNamn`, `Typ`, `Muskelgrupp`) VALUES
('21:an', 'isolated', 'Arms'),
('abduction', 'isolated', 'Legs'),
('adduction', 'isolated', 'Legs'),
('Arm Exercise 1', 'compound', 'Arms'),
('Arm Exercise 10', 'isolated', 'Arms'),
('Arm Exercise 100', 'isolated', 'Arms'),
('Arm Exercise 11', 'compound', 'Arms'),
('Arm Exercise 12', 'isolated', 'Arms'),
('Arm Exercise 13', 'compound', 'Arms'),
('Arm Exercise 14', 'isolated', 'Arms'),
('Arm Exercise 15', 'compound', 'Arms'),
('Arm Exercise 16', 'isolated', 'Arms'),
('Arm Exercise 17', 'compound', 'Arms'),
('Arm Exercise 18', 'isolated', 'Arms'),
('Arm Exercise 19', 'compound', 'Arms'),
('Arm Exercise 2', 'isolated', 'Arms'),
('Arm Exercise 20', 'isolated', 'Arms'),
('Arm Exercise 21', 'compound', 'Arms'),
('Arm Exercise 22', 'isolated', 'Arms'),
('Arm Exercise 23', 'compound', 'Arms'),
('Arm Exercise 24', 'isolated', 'Arms'),
('Arm Exercise 25', 'compound', 'Arms'),
('Arm Exercise 26', 'isolated', 'Arms'),
('Arm Exercise 27', 'compound', 'Arms'),
('Arm Exercise 28', 'isolated', 'Arms'),
('Arm Exercise 29', 'compound', 'Arms'),
('Arm Exercise 3', 'compound', 'Arms'),
('Arm Exercise 30', 'isolated', 'Arms'),
('Arm Exercise 31', 'compound', 'Arms'),
('Arm Exercise 32', 'isolated', 'Arms'),
('Arm Exercise 33', 'compound', 'Arms'),
('Arm Exercise 34', 'isolated', 'Arms'),
('Arm Exercise 35', 'compound', 'Arms'),
('Arm Exercise 36', 'isolated', 'Arms'),
('Arm Exercise 37', 'compound', 'Arms'),
('Arm Exercise 38', 'isolated', 'Arms'),
('Arm Exercise 39', 'compound', 'Arms'),
('Arm Exercise 4', 'isolated', 'Arms'),
('Arm Exercise 40', 'isolated', 'Arms'),
('Arm Exercise 41', 'compound', 'Arms'),
('Arm Exercise 42', 'isolated', 'Arms'),
('Arm Exercise 43', 'compound', 'Arms'),
('Arm Exercise 44', 'isolated', 'Arms'),
('Arm Exercise 45', 'compound', 'Arms'),
('Arm Exercise 46', 'isolated', 'Arms'),
('Arm Exercise 47', 'compound', 'Arms'),
('Arm Exercise 48', 'isolated', 'Arms'),
('Arm Exercise 49', 'compound', 'Arms'),
('Arm Exercise 5', 'compound', 'Arms'),
('Arm Exercise 50', 'isolated', 'Arms'),
('Arm Exercise 51', 'compound', 'Arms'),
('Arm Exercise 52', 'isolated', 'Arms'),
('Arm Exercise 53', 'compound', 'Arms'),
('Arm Exercise 54', 'isolated', 'Arms'),
('Arm Exercise 55', 'compound', 'Arms'),
('Arm Exercise 56', 'isolated', 'Arms'),
('Arm Exercise 57', 'compound', 'Arms'),
('Arm Exercise 58', 'isolated', 'Arms'),
('Arm Exercise 59', 'compound', 'Arms'),
('Arm Exercise 6', 'isolated', 'Arms'),
('Arm Exercise 60', 'isolated', 'Arms'),
('Arm Exercise 61', 'compound', 'Arms'),
('Arm Exercise 62', 'isolated', 'Arms'),
('Arm Exercise 63', 'compound', 'Arms'),
('Arm Exercise 64', 'isolated', 'Arms'),
('Arm Exercise 65', 'compound', 'Arms'),
('Arm Exercise 66', 'isolated', 'Arms'),
('Arm Exercise 67', 'compound', 'Arms'),
('Arm Exercise 68', 'isolated', 'Arms'),
('Arm Exercise 69', 'compound', 'Arms'),
('Arm Exercise 7', 'compound', 'Arms'),
('Arm Exercise 70', 'isolated', 'Arms'),
('Arm Exercise 71', 'compound', 'Arms'),
('Arm Exercise 72', 'isolated', 'Arms'),
('Arm Exercise 73', 'compound', 'Arms'),
('Arm Exercise 74', 'isolated', 'Arms'),
('Arm Exercise 75', 'compound', 'Arms'),
('Arm Exercise 76', 'isolated', 'Arms'),
('Arm Exercise 77', 'compound', 'Arms'),
('Arm Exercise 78', 'isolated', 'Arms'),
('Arm Exercise 79', 'compound', 'Arms'),
('Arm Exercise 8', 'isolated', 'Arms'),
('Arm Exercise 80', 'isolated', 'Arms'),
('Arm Exercise 81', 'compound', 'Arms'),
('Arm Exercise 82', 'isolated', 'Arms'),
('Arm Exercise 83', 'compound', 'Arms'),
('Arm Exercise 84', 'isolated', 'Arms'),
('Arm Exercise 85', 'compound', 'Arms'),
('Arm Exercise 86', 'isolated', 'Arms'),
('Arm Exercise 87', 'compound', 'Arms'),
('Arm Exercise 88', 'isolated', 'Arms'),
('Arm Exercise 89', 'compound', 'Arms'),
('Arm Exercise 9', 'compound', 'Arms'),
('Arm Exercise 90', 'isolated', 'Arms'),
('Arm Exercise 91', 'compound', 'Arms'),
('Arm Exercise 92', 'isolated', 'Arms'),
('Arm Exercise 93', 'compound', 'Arms'),
('Arm Exercise 94', 'isolated', 'Arms'),
('Arm Exercise 95', 'compound', 'Arms'),
('Arm Exercise 96', 'isolated', 'Arms'),
('Arm Exercise 97', 'compound', 'Arms'),
('Arm Exercise 98', 'isolated', 'Arms'),
('Arm Exercise 99', 'compound', 'Arms'),
('Arnold press', 'compound', 'Shoulders'),
('Around the world', 'compound', 'Shoulders'),
('Back Exercise 1', 'compound', 'Back'),
('Back Exercise 10', 'isolated', 'Back'),
('Back Exercise 100', 'isolated', 'Back'),
('Back Exercise 11', 'compound', 'Back'),
('Back Exercise 12', 'isolated', 'Back'),
('Back Exercise 13', 'compound', 'Back'),
('Back Exercise 14', 'isolated', 'Back'),
('Back Exercise 15', 'compound', 'Back'),
('Back Exercise 16', 'isolated', 'Back'),
('Back Exercise 17', 'compound', 'Back'),
('Back Exercise 18', 'isolated', 'Back'),
('Back Exercise 19', 'compound', 'Back'),
('Back Exercise 2', 'isolated', 'Back'),
('Back Exercise 20', 'isolated', 'Back'),
('Back Exercise 21', 'compound', 'Back'),
('Back Exercise 22', 'isolated', 'Back'),
('Back Exercise 23', 'compound', 'Back'),
('Back Exercise 24', 'isolated', 'Back'),
('Back Exercise 25', 'compound', 'Back'),
('Back Exercise 26', 'isolated', 'Back'),
('Back Exercise 27', 'compound', 'Back'),
('Back Exercise 28', 'isolated', 'Back'),
('Back Exercise 29', 'compound', 'Back'),
('Back Exercise 3', 'compound', 'Back'),
('Back Exercise 30', 'isolated', 'Back'),
('Back Exercise 31', 'compound', 'Back'),
('Back Exercise 32', 'isolated', 'Back'),
('Back Exercise 33', 'compound', 'Back'),
('Back Exercise 34', 'isolated', 'Back'),
('Back Exercise 35', 'compound', 'Back'),
('Back Exercise 36', 'isolated', 'Back'),
('Back Exercise 37', 'compound', 'Back'),
('Back Exercise 38', 'isolated', 'Back'),
('Back Exercise 39', 'compound', 'Back'),
('Back Exercise 4', 'isolated', 'Back'),
('Back Exercise 40', 'isolated', 'Back'),
('Back Exercise 41', 'compound', 'Back'),
('Back Exercise 42', 'isolated', 'Back'),
('Back Exercise 43', 'compound', 'Back'),
('Back Exercise 44', 'isolated', 'Back'),
('Back Exercise 45', 'compound', 'Back'),
('Back Exercise 46', 'isolated', 'Back'),
('Back Exercise 47', 'compound', 'Back'),
('Back Exercise 48', 'isolated', 'Back'),
('Back Exercise 49', 'compound', 'Back'),
('Back Exercise 5', 'compound', 'Back'),
('Back Exercise 50', 'isolated', 'Back'),
('Back Exercise 51', 'compound', 'Back'),
('Back Exercise 52', 'isolated', 'Back'),
('Back Exercise 53', 'compound', 'Back'),
('Back Exercise 54', 'isolated', 'Back'),
('Back Exercise 55', 'compound', 'Back'),
('Back Exercise 56', 'isolated', 'Back'),
('Back Exercise 57', 'compound', 'Back'),
('Back Exercise 58', 'isolated', 'Back'),
('Back Exercise 59', 'compound', 'Back'),
('Back Exercise 6', 'isolated', 'Back'),
('Back Exercise 60', 'isolated', 'Back'),
('Back Exercise 61', 'compound', 'Back'),
('Back Exercise 62', 'isolated', 'Back'),
('Back Exercise 63', 'compound', 'Back'),
('Back Exercise 64', 'isolated', 'Back'),
('Back Exercise 65', 'compound', 'Back'),
('Back Exercise 66', 'isolated', 'Back'),
('Back Exercise 67', 'compound', 'Back'),
('Back Exercise 68', 'isolated', 'Back'),
('Back Exercise 69', 'compound', 'Back'),
('Back Exercise 7', 'compound', 'Back'),
('Back Exercise 70', 'isolated', 'Back'),
('Back Exercise 71', 'compound', 'Back'),
('Back Exercise 72', 'isolated', 'Back'),
('Back Exercise 73', 'compound', 'Back'),
('Back Exercise 74', 'isolated', 'Back'),
('Back Exercise 75', 'compound', 'Back'),
('Back Exercise 76', 'isolated', 'Back'),
('Back Exercise 77', 'compound', 'Back'),
('Back Exercise 78', 'isolated', 'Back'),
('Back Exercise 79', 'compound', 'Back'),
('Back Exercise 8', 'isolated', 'Back'),
('Back Exercise 80', 'isolated', 'Back'),
('Back Exercise 81', 'compound', 'Back'),
('Back Exercise 82', 'isolated', 'Back'),
('Back Exercise 83', 'compound', 'Back'),
('Back Exercise 84', 'isolated', 'Back'),
('Back Exercise 85', 'compound', 'Back'),
('Back Exercise 86', 'isolated', 'Back'),
('Back Exercise 87', 'compound', 'Back'),
('Back Exercise 88', 'isolated', 'Back'),
('Back Exercise 89', 'compound', 'Back'),
('Back Exercise 9', 'compound', 'Back'),
('Back Exercise 90', 'isolated', 'Back'),
('Back Exercise 91', 'compound', 'Back'),
('Back Exercise 92', 'isolated', 'Back'),
('Back Exercise 93', 'compound', 'Back'),
('Back Exercise 94', 'isolated', 'Back'),
('Back Exercise 95', 'compound', 'Back'),
('Back Exercise 96', 'isolated', 'Back'),
('Back Exercise 97', 'compound', 'Back'),
('Back Exercise 98', 'isolated', 'Back'),
('Back Exercise 99', 'compound', 'Back'),
('Back extension', 'isolated', 'Back'),
('Barbell shoulder press', 'isolated', 'Shoulders'),
('BB rows', 'isolated', 'Back'),
('BB upright row', 'isolated', 'Shoulders'),
('Bench Press', 'compound', 'Chest'),
('Bicep Curls', 'isolated', 'Arms'),
('Bulgarian split-sqauts', 'compound', 'Legs'),
('Cable flyes', 'isolated', 'Chest'),
('Cable rows', 'isolated', 'Back'),
('Cable upright row', 'isolated', 'Shoulders'),
('Calf Raise', 'isolated', 'Legs'),
('Chest Exercise 1', 'compound', 'Chest'),
('Chest Exercise 10', 'isolated', 'Chest'),
('Chest Exercise 100', 'isolated', 'Chest'),
('Chest Exercise 11', 'compound', 'Chest'),
('Chest Exercise 12', 'isolated', 'Chest'),
('Chest Exercise 13', 'compound', 'Chest'),
('Chest Exercise 14', 'isolated', 'Chest'),
('Chest Exercise 15', 'compound', 'Chest'),
('Chest Exercise 16', 'isolated', 'Chest'),
('Chest Exercise 17', 'compound', 'Chest'),
('Chest Exercise 18', 'isolated', 'Chest'),
('Chest Exercise 19', 'compound', 'Chest'),
('Chest Exercise 2', 'isolated', 'Chest'),
('Chest Exercise 20', 'isolated', 'Chest'),
('Chest Exercise 21', 'compound', 'Chest'),
('Chest Exercise 22', 'isolated', 'Chest'),
('Chest Exercise 23', 'compound', 'Chest'),
('Chest Exercise 24', 'isolated', 'Chest'),
('Chest Exercise 25', 'compound', 'Chest'),
('Chest Exercise 26', 'isolated', 'Chest'),
('Chest Exercise 27', 'compound', 'Chest'),
('Chest Exercise 28', 'isolated', 'Chest'),
('Chest Exercise 29', 'compound', 'Chest'),
('Chest Exercise 3', 'compound', 'Chest'),
('Chest Exercise 30', 'isolated', 'Chest'),
('Chest Exercise 31', 'compound', 'Chest'),
('Chest Exercise 32', 'isolated', 'Chest'),
('Chest Exercise 33', 'compound', 'Chest'),
('Chest Exercise 34', 'isolated', 'Chest'),
('Chest Exercise 35', 'compound', 'Chest'),
('Chest Exercise 36', 'isolated', 'Chest'),
('Chest Exercise 37', 'compound', 'Chest'),
('Chest Exercise 38', 'isolated', 'Chest'),
('Chest Exercise 39', 'compound', 'Chest'),
('Chest Exercise 4', 'isolated', 'Chest'),
('Chest Exercise 40', 'isolated', 'Chest'),
('Chest Exercise 41', 'compound', 'Chest'),
('Chest Exercise 42', 'isolated', 'Chest'),
('Chest Exercise 43', 'compound', 'Chest'),
('Chest Exercise 44', 'isolated', 'Chest'),
('Chest Exercise 45', 'compound', 'Chest'),
('Chest Exercise 46', 'isolated', 'Chest'),
('Chest Exercise 47', 'compound', 'Chest'),
('Chest Exercise 48', 'isolated', 'Chest'),
('Chest Exercise 49', 'compound', 'Chest'),
('Chest Exercise 5', 'compound', 'Chest'),
('Chest Exercise 50', 'isolated', 'Chest'),
('Chest Exercise 51', 'compound', 'Chest'),
('Chest Exercise 52', 'isolated', 'Chest'),
('Chest Exercise 53', 'compound', 'Chest'),
('Chest Exercise 54', 'isolated', 'Chest'),
('Chest Exercise 55', 'compound', 'Chest'),
('Chest Exercise 56', 'isolated', 'Chest'),
('Chest Exercise 57', 'compound', 'Chest'),
('Chest Exercise 58', 'isolated', 'Chest'),
('Chest Exercise 59', 'compound', 'Chest'),
('Chest Exercise 6', 'isolated', 'Chest'),
('Chest Exercise 60', 'isolated', 'Chest'),
('Chest Exercise 61', 'compound', 'Chest'),
('Chest Exercise 62', 'isolated', 'Chest'),
('Chest Exercise 63', 'compound', 'Chest'),
('Chest Exercise 64', 'isolated', 'Chest'),
('Chest Exercise 65', 'compound', 'Chest'),
('Chest Exercise 66', 'isolated', 'Chest'),
('Chest Exercise 67', 'compound', 'Chest'),
('Chest Exercise 68', 'isolated', 'Chest'),
('Chest Exercise 69', 'compound', 'Chest'),
('Chest Exercise 7', 'compound', 'Chest'),
('Chest Exercise 70', 'isolated', 'Chest'),
('Chest Exercise 71', 'compound', 'Chest'),
('Chest Exercise 72', 'isolated', 'Chest'),
('Chest Exercise 73', 'compound', 'Chest'),
('Chest Exercise 74', 'isolated', 'Chest'),
('Chest Exercise 75', 'compound', 'Chest'),
('Chest Exercise 76', 'isolated', 'Chest'),
('Chest Exercise 77', 'compound', 'Chest'),
('Chest Exercise 78', 'isolated', 'Chest'),
('Chest Exercise 79', 'compound', 'Chest'),
('Chest Exercise 8', 'isolated', 'Chest'),
('Chest Exercise 80', 'isolated', 'Chest'),
('Chest Exercise 81', 'compound', 'Chest'),
('Chest Exercise 82', 'isolated', 'Chest'),
('Chest Exercise 83', 'compound', 'Chest'),
('Chest Exercise 84', 'isolated', 'Chest'),
('Chest Exercise 85', 'compound', 'Chest'),
('Chest Exercise 86', 'isolated', 'Chest'),
('Chest Exercise 87', 'compound', 'Chest'),
('Chest Exercise 88', 'isolated', 'Chest'),
('Chest Exercise 89', 'compound', 'Chest'),
('Chest Exercise 9', 'compound', 'Chest'),
('Chest Exercise 90', 'isolated', 'Chest'),
('Chest Exercise 91', 'compound', 'Chest'),
('Chest Exercise 92', 'isolated', 'Chest'),
('Chest Exercise 93', 'compound', 'Chest'),
('Chest Exercise 94', 'isolated', 'Chest'),
('Chest Exercise 95', 'compound', 'Chest'),
('Chest Exercise 96', 'isolated', 'Chest'),
('Chest Exercise 97', 'compound', 'Chest'),
('Chest Exercise 98', 'isolated', 'Chest'),
('Chest Exercise 99', 'compound', 'Chest'),
('Crossrack cable pull', 'isolated', 'Back'),
('DB butterflies', 'isolated', 'Shoulders'),
('DB chestpress', 'compound', 'Chest'),
('DB curls', 'isolated', 'Arms'),
('DB flyes', 'isolated', 'Chest'),
('DB pull over', 'isolated', 'Chest'),
('DB rows', 'isolated', 'Back'),
('DB shoulder press', 'compound', 'Shoulders'),
('DB upright row', 'isolated', 'Shoulders'),
('Deadlifts', 'compound', 'Legs'),
('Dips', 'compound', 'Arms'),
('Eccentric leg-curls', 'isolated', 'Legs'),
('EZ-bar curls', 'compound', 'Arms'),
('EZ-bar front raise', 'isolated', 'Shoulders'),
('Front lateral raise', 'isolated', 'Shoulders'),
('goblet squats', 'compound', 'Legs'),
('Hammercurls', 'isolated', 'Arms'),
('Hip thrusts', 'compound', 'Legs'),
('Incline DB bench curls', 'compound', 'Arms'),
('Incline front raise', 'isolated', 'Shoulders'),
('Jump Squats', 'compound', 'Legs'),
('Kickbacks', 'isolated', 'Legs'),
('Landmine press', 'compound', 'Chest'),
('Leg Exercise 1', 'compound', 'Legs'),
('Leg Exercise 10', 'isolated', 'Legs'),
('Leg Exercise 100', 'isolated', 'Legs'),
('Leg Exercise 11', 'compound', 'Legs'),
('Leg Exercise 12', 'isolated', 'Legs'),
('Leg Exercise 13', 'compound', 'Legs'),
('Leg Exercise 14', 'isolated', 'Legs'),
('Leg Exercise 15', 'compound', 'Legs'),
('Leg Exercise 16', 'isolated', 'Legs'),
('Leg Exercise 17', 'compound', 'Legs'),
('Leg Exercise 18', 'isolated', 'Legs'),
('Leg Exercise 19', 'compound', 'Legs'),
('Leg Exercise 2', 'isolated', 'Legs'),
('Leg Exercise 20', 'isolated', 'Legs'),
('Leg Exercise 21', 'compound', 'Legs'),
('Leg Exercise 22', 'isolated', 'Legs'),
('Leg Exercise 23', 'compound', 'Legs'),
('Leg Exercise 24', 'isolated', 'Legs'),
('Leg Exercise 25', 'compound', 'Legs'),
('Leg Exercise 26', 'isolated', 'Legs'),
('Leg Exercise 27', 'compound', 'Legs'),
('Leg Exercise 28', 'isolated', 'Legs'),
('Leg Exercise 29', 'compound', 'Legs'),
('Leg Exercise 3', 'compound', 'Legs'),
('Leg Exercise 30', 'isolated', 'Legs'),
('Leg Exercise 31', 'compound', 'Legs'),
('Leg Exercise 32', 'isolated', 'Legs'),
('Leg Exercise 33', 'compound', 'Legs'),
('Leg Exercise 34', 'isolated', 'Legs'),
('Leg Exercise 35', 'compound', 'Legs'),
('Leg Exercise 36', 'isolated', 'Legs'),
('Leg Exercise 37', 'compound', 'Legs'),
('Leg Exercise 38', 'isolated', 'Legs'),
('Leg Exercise 39', 'compound', 'Legs'),
('Leg Exercise 4', 'isolated', 'Legs'),
('Leg Exercise 40', 'isolated', 'Legs'),
('Leg Exercise 41', 'compound', 'Legs'),
('Leg Exercise 42', 'isolated', 'Legs'),
('Leg Exercise 43', 'compound', 'Legs'),
('Leg Exercise 44', 'isolated', 'Legs'),
('Leg Exercise 45', 'compound', 'Legs'),
('Leg Exercise 46', 'isolated', 'Legs'),
('Leg Exercise 47', 'compound', 'Legs'),
('Leg Exercise 48', 'isolated', 'Legs'),
('Leg Exercise 49', 'compound', 'Legs'),
('Leg Exercise 5', 'compound', 'Legs'),
('Leg Exercise 50', 'isolated', 'Legs'),
('Leg Exercise 51', 'compound', 'Legs'),
('Leg Exercise 52', 'isolated', 'Legs'),
('Leg Exercise 53', 'compound', 'Legs'),
('Leg Exercise 54', 'isolated', 'Legs'),
('Leg Exercise 55', 'compound', 'Legs'),
('Leg Exercise 56', 'isolated', 'Legs'),
('Leg Exercise 57', 'compound', 'Legs'),
('Leg Exercise 58', 'isolated', 'Legs'),
('Leg Exercise 59', 'compound', 'Legs'),
('Leg Exercise 6', 'isolated', 'Legs'),
('Leg Exercise 60', 'isolated', 'Legs'),
('Leg Exercise 61', 'compound', 'Legs'),
('Leg Exercise 62', 'isolated', 'Legs'),
('Leg Exercise 63', 'compound', 'Legs'),
('Leg Exercise 64', 'isolated', 'Legs'),
('Leg Exercise 65', 'compound', 'Legs'),
('Leg Exercise 66', 'isolated', 'Legs'),
('Leg Exercise 67', 'compound', 'Legs'),
('Leg Exercise 68', 'isolated', 'Legs'),
('Leg Exercise 69', 'compound', 'Legs'),
('Leg Exercise 7', 'compound', 'Legs'),
('Leg Exercise 70', 'isolated', 'Legs'),
('Leg Exercise 71', 'compound', 'Legs'),
('Leg Exercise 72', 'isolated', 'Legs'),
('Leg Exercise 73', 'compound', 'Legs'),
('Leg Exercise 74', 'isolated', 'Legs'),
('Leg Exercise 75', 'compound', 'Legs'),
('Leg Exercise 76', 'isolated', 'Legs'),
('Leg Exercise 77', 'compound', 'Legs'),
('Leg Exercise 78', 'isolated', 'Legs'),
('Leg Exercise 79', 'compound', 'Legs'),
('Leg Exercise 8', 'isolated', 'Legs'),
('Leg Exercise 80', 'isolated', 'Legs'),
('Leg Exercise 81', 'compound', 'Legs'),
('Leg Exercise 82', 'isolated', 'Legs'),
('Leg Exercise 83', 'compound', 'Legs'),
('Leg Exercise 84', 'isolated', 'Legs'),
('Leg Exercise 85', 'compound', 'Legs'),
('Leg Exercise 86', 'isolated', 'Legs'),
('Leg Exercise 87', 'compound', 'Legs'),
('Leg Exercise 88', 'isolated', 'Legs'),
('Leg Exercise 89', 'compound', 'Legs'),
('Leg Exercise 9', 'compound', 'Legs'),
('Leg Exercise 90', 'isolated', 'Legs'),
('Leg Exercise 91', 'compound', 'Legs'),
('Leg Exercise 92', 'isolated', 'Legs'),
('Leg Exercise 93', 'compound', 'Legs'),
('Leg Exercise 94', 'isolated', 'Legs'),
('Leg Exercise 95', 'compound', 'Legs'),
('Leg Exercise 96', 'isolated', 'Legs'),
('Leg Exercise 97', 'compound', 'Legs'),
('Leg Exercise 98', 'isolated', 'Legs'),
('Leg Exercise 99', 'compound', 'Legs'),
('Leg extension', 'isolated', 'Legs'),
('Leg Raises', 'isolated', 'Legs'),
('Legpress', 'compound', 'Legs'),
('Lunges', 'compound', 'Legs'),
('Lying leg-curls', 'isolated', 'Legs'),
('Military press', 'compound', 'Shoulders'),
('Mountain Climbers', 'isolated', 'Legs'),
('Overhead extension', 'compound', 'Arms'),
('Paralell front raise', 'isolated', 'Shoulders'),
('Plate press up', 'isolated', 'Chest'),
('Pull-ups', 'compound', 'Back'),
('Push-ups', 'compound', 'Arms'),
('Reversed cable flyes', 'isolated', 'Shoulders'),
('Rope curls', 'isolated', 'Arms'),
('Rope face-pull', 'isolated', 'Shoulders'),
('Seated calf raise', 'isolated', 'Legs'),
('Shoulder Exercise 1', 'compound', 'Shoulders'),
('Shoulder Exercise 10', 'isolated', 'Shoulders'),
('Shoulder Exercise 100', 'isolated', 'Shoulders'),
('Shoulder Exercise 11', 'compound', 'Shoulders'),
('Shoulder Exercise 12', 'isolated', 'Shoulders'),
('Shoulder Exercise 13', 'compound', 'Shoulders'),
('Shoulder Exercise 14', 'isolated', 'Shoulders'),
('Shoulder Exercise 15', 'compound', 'Shoulders'),
('Shoulder Exercise 16', 'isolated', 'Shoulders'),
('Shoulder Exercise 17', 'compound', 'Shoulders'),
('Shoulder Exercise 18', 'isolated', 'Shoulders'),
('Shoulder Exercise 19', 'compound', 'Shoulders'),
('Shoulder Exercise 2', 'isolated', 'Shoulders'),
('Shoulder Exercise 20', 'isolated', 'Shoulders'),
('Shoulder Exercise 21', 'compound', 'Shoulders'),
('Shoulder Exercise 22', 'isolated', 'Shoulders'),
('Shoulder Exercise 23', 'compound', 'Shoulders'),
('Shoulder Exercise 24', 'isolated', 'Shoulders'),
('Shoulder Exercise 25', 'compound', 'Shoulders'),
('Shoulder Exercise 26', 'isolated', 'Shoulders'),
('Shoulder Exercise 27', 'compound', 'Shoulders'),
('Shoulder Exercise 28', 'isolated', 'Shoulders'),
('Shoulder Exercise 29', 'compound', 'Shoulders'),
('Shoulder Exercise 3', 'compound', 'Shoulders'),
('Shoulder Exercise 30', 'isolated', 'Shoulders'),
('Shoulder Exercise 31', 'compound', 'Shoulders'),
('Shoulder Exercise 32', 'isolated', 'Shoulders'),
('Shoulder Exercise 33', 'compound', 'Shoulders'),
('Shoulder Exercise 34', 'isolated', 'Shoulders'),
('Shoulder Exercise 35', 'compound', 'Shoulders'),
('Shoulder Exercise 36', 'isolated', 'Shoulders'),
('Shoulder Exercise 37', 'compound', 'Shoulders'),
('Shoulder Exercise 38', 'isolated', 'Shoulders'),
('Shoulder Exercise 39', 'compound', 'Shoulders'),
('Shoulder Exercise 4', 'isolated', 'Shoulders'),
('Shoulder Exercise 40', 'isolated', 'Shoulders'),
('Shoulder Exercise 41', 'compound', 'Shoulders'),
('Shoulder Exercise 42', 'isolated', 'Shoulders'),
('Shoulder Exercise 43', 'compound', 'Shoulders'),
('Shoulder Exercise 44', 'isolated', 'Shoulders'),
('Shoulder Exercise 45', 'compound', 'Shoulders'),
('Shoulder Exercise 46', 'isolated', 'Shoulders'),
('Shoulder Exercise 47', 'compound', 'Shoulders'),
('Shoulder Exercise 48', 'isolated', 'Shoulders'),
('Shoulder Exercise 49', 'compound', 'Shoulders'),
('Shoulder Exercise 5', 'compound', 'Shoulders'),
('Shoulder Exercise 50', 'isolated', 'Shoulders'),
('Shoulder Exercise 51', 'compound', 'Shoulders'),
('Shoulder Exercise 52', 'isolated', 'Shoulders'),
('Shoulder Exercise 53', 'compound', 'Shoulders'),
('Shoulder Exercise 54', 'isolated', 'Shoulders'),
('Shoulder Exercise 55', 'compound', 'Shoulders'),
('Shoulder Exercise 56', 'isolated', 'Shoulders'),
('Shoulder Exercise 57', 'compound', 'Shoulders'),
('Shoulder Exercise 58', 'isolated', 'Shoulders'),
('Shoulder Exercise 59', 'compound', 'Shoulders'),
('Shoulder Exercise 6', 'isolated', 'Shoulders'),
('Shoulder Exercise 60', 'isolated', 'Shoulders'),
('Shoulder Exercise 61', 'compound', 'Shoulders'),
('Shoulder Exercise 62', 'isolated', 'Shoulders'),
('Shoulder Exercise 63', 'compound', 'Shoulders'),
('Shoulder Exercise 64', 'isolated', 'Shoulders'),
('Shoulder Exercise 65', 'compound', 'Shoulders'),
('Shoulder Exercise 66', 'isolated', 'Shoulders'),
('Shoulder Exercise 67', 'compound', 'Shoulders'),
('Shoulder Exercise 68', 'isolated', 'Shoulders'),
('Shoulder Exercise 69', 'compound', 'Shoulders'),
('Shoulder Exercise 7', 'compound', 'Shoulders'),
('Shoulder Exercise 70', 'isolated', 'Shoulders'),
('Shoulder Exercise 71', 'compound', 'Shoulders'),
('Shoulder Exercise 72', 'isolated', 'Shoulders'),
('Shoulder Exercise 73', 'compound', 'Shoulders'),
('Shoulder Exercise 74', 'isolated', 'Shoulders'),
('Shoulder Exercise 75', 'compound', 'Shoulders'),
('Shoulder Exercise 76', 'isolated', 'Shoulders'),
('Shoulder Exercise 77', 'compound', 'Shoulders'),
('Shoulder Exercise 78', 'isolated', 'Shoulders'),
('Shoulder Exercise 79', 'compound', 'Shoulders'),
('Shoulder Exercise 8', 'isolated', 'Shoulders'),
('Shoulder Exercise 80', 'isolated', 'Shoulders'),
('Shoulder Exercise 81', 'compound', 'Shoulders'),
('Shoulder Exercise 82', 'isolated', 'Shoulders'),
('Shoulder Exercise 83', 'compound', 'Shoulders'),
('Shoulder Exercise 84', 'isolated', 'Shoulders'),
('Shoulder Exercise 85', 'compound', 'Shoulders'),
('Shoulder Exercise 86', 'isolated', 'Shoulders'),
('Shoulder Exercise 87', 'compound', 'Shoulders'),
('Shoulder Exercise 88', 'isolated', 'Shoulders'),
('Shoulder Exercise 89', 'compound', 'Shoulders'),
('Shoulder Exercise 9', 'compound', 'Shoulders'),
('Shoulder Exercise 90', 'isolated', 'Shoulders'),
('Shoulder Exercise 91', 'compound', 'Shoulders'),
('Shoulder Exercise 92', 'isolated', 'Shoulders'),
('Shoulder Exercise 93', 'compound', 'Shoulders'),
('Shoulder Exercise 94', 'isolated', 'Shoulders'),
('Shoulder Exercise 95', 'compound', 'Shoulders'),
('Shoulder Exercise 96', 'isolated', 'Shoulders'),
('Shoulder Exercise 97', 'compound', 'Shoulders'),
('Shoulder Exercise 98', 'isolated', 'Shoulders'),
('Shoulder Exercise 99', 'compound', 'Shoulders'),
('Shoulder Press', 'compound', 'Shoulders'),
('Side lateral raise', 'isolated', 'Shoulders'),
('Skull crushers', 'compound', 'Arms'),
('Smith sumo-squats', 'compound', 'Legs'),
('Spidercurls', 'compound', 'Arms'),
('Spinning wheel', 'compound', 'Shoulders'),
('Squats', 'compound', 'Legs'),
('Step-ups', 'compound', 'Legs'),
('Stiffed leg deadlifts', 'isolated', 'Legs'),
('Straight arm pulldown', 'isolated', 'Back'),
('Sumo deadlift', 'compound', 'Back'),
('T-bar row', 'compound', 'Back'),
('Tricep extension', 'isolated', 'Arms'),
('Underarm cable rows', 'compound', 'Back'),
('V-pulldown', 'compound', 'Back'),
('Walking lunges', 'compound', 'Legs'),
('Wide lat pulldown', 'compound', 'Back');

CREATE TABLE `övningsrelation` (
  `ÖvningsRelations-ID` int(11) NOT NULL,
  `Program-ID` int(11) NOT NULL,
  `ÖvningsNamn` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `login`
  ADD PRIMARY KEY (`username`);

ALTER TABLE `träningskategori`
  ADD PRIMARY KEY (`KategoriNamn`);

ALTER TABLE `träningsprogram`
  ADD PRIMARY KEY (`Program-ID`),
  ADD KEY `KategoriNam` (`KategoriNamn`),
  ADD KEY `username` (`username`);

ALTER TABLE `träningsövning`
  ADD PRIMARY KEY (`ÖvningsNamn`);

ALTER TABLE `övningsrelation`
  ADD PRIMARY KEY (`ÖvningsRelations-ID`),
  ADD KEY `Program-ID` (`Program-ID`),
  ADD KEY `ÖvningsNamn` (`ÖvningsNamn`);

ALTER TABLE `historik`
  ADD CONSTRAINT `historik_ibfk_1` FOREIGN KEY (`username`) REFERENCES `login` (`username`);

ALTER TABLE `träningsprogram`
  ADD CONSTRAINT `träningsprogram_ibfk_1` FOREIGN KEY (`KategoriNamn`) REFERENCES `träningskategori` (`KategoriNamn`),
  ADD CONSTRAINT `träningsprogram_ibfk_2` FOREIGN KEY (`username`) REFERENCES `login` (`username`);


ALTER TABLE `övningsrelation`
  ADD CONSTRAINT `övningsrelation_ibfk_1` FOREIGN KEY (`Program-ID`) REFERENCES `träningsprogram` (`Program-ID`),
  ADD CONSTRAINT `övningsrelation_ibfk_2` FOREIGN KEY (`ÖvningsNamn`) REFERENCES `träningsövning` (`ÖvningsNamn`);
COMMIT;
